shgram/apis/urls.py
from django.urls import path

from apis.views import (
    UserCreateView, UserLoginView, UserLogoutView, ContentCreateView, RelationCreateView, RelationDeleteView,
    UserGetView
)
urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/login', UserLoginView.as_view(), name='user_login'),
    path('users/logout', UserLogoutView.as_view(), name='user_logout'),
    path('users/contentCreate', ContentCreateView.as_view(), name='content_create'),
    path('users/relations/create',
         RelationCreateView.as_view(), name='relation_create'),
    path('users/relations/delete',
         RelationDeleteView.as_view(), name='relation_delete'),
    path('users/get', UserGetView.as_view(), name='users_get_info'),

]

shgram/shgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

from contents.views import HomeView, RelationView


class NonUserTemplateView(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_anonymous:
            return redirect('home')
        return super(NonUserTemplateView, self).dispatch(request, *args, **kwargs)


# name에 설정 된부분이 html과 연결된다.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('apis/', include('apis.urls')),
    path('', HomeView.as_view(), name='home'),
    path('login/', NonUserTemplateView.as_view(template_name='login.html'), name='login'),
    path('register/', NonUserTemplateView.as_view(template_name='register.html'),
         name='register'),
    path('relation/', RelationView.as_view(), name='relation'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
# 미디어 세팅
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shgram/contents/models.py
import os
import uuid

from django.db import models
from django.contrib.auth.models import User


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Content(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(default='')

    class Meta:
        # 최신글 먼저나오게
        ordering = ['-created_at']
        verbose_name_plural = "컨텐츠"


def image_upload_to(instance, filename):
    ext = filename.split('.')[-1]
    print(uuid.uuid4(), ext)
    return os.path.join(instance.UPLOAD_PATH, "%s.%s" % (uuid.uuid4(), ext))

    # 16자리 고유한 아이디 생성


class Image(BaseModel):
    UPLOAD_PATH = 'user-upload'

    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload_to)
    order = models.SmallIntegerField()  # image numbering

    class Meta:
        unique_together = ['content', 'order']
        ordering = ['order']
        verbose_name_plural = "이미지"


class FollowRelation(BaseModel):
    follower = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='follower')
    followee = models.ManyToManyField(User, related_name='followee')

shgram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static '/css/register.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <title>{% block title %}{% endblock %}</title>
    {% block head %}
    {% endblock %}
</head>

<body>
    {% block body %}
    {% endblock %}
</body>

</html>

shgram/templates/header.html
{% extends "base.html" %}

{% block body %}
<nav class="fast-nav navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-brand text-warning col-sm-8" href="{% url 'home' %}">
        <img src="/media/user-upload/1600007369751.png" width='30' height="30" class="d-inline-block align-top"
            alt="">shgram</a>
    <div class="collapse navbar-collapse col-sm-4" id="navbarText"
        style="display: inline-block !important; text-align: left;">
        <span class="navbar-text col-sm-3">
            {{ request.user }}
        </span>
        <span class="navbar-text col-sm-3">
            <a href="{% url 'relation' %}">친구목록</a>
        </span>
        <span class="navbar-text col-sm-3">
            <a href="javascript:void(0);" id="logout">로그아웃</a>
        </span>
    </div>
</nav>

<br>

{% endblock %}

shgram/templates/home.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/dropzone@5.5.1/dist/dropzone.min.css">

{% endblock %}


{% block body %}
<nav class="fast-nav navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-brand text-warning col-sm-8" href="{% url 'home' %}">
        <img src="/media/user-upload/1600007369751.png" width='30' height="30" class="d-inline-block align-top"
            alt="">shgram</a>
    <div class="collapse navbar-collapse col-sm-4" id="navbarText"
        style="display: inline-block !important; text-align: left;">
        <span class="navbar-text col-sm-3">
            {{ request.user }}
        </span>
        <span class="navbar-text col-sm-3">
            <a href="{% url 'relation' %}">친구목록</a>
        </span>
        <span class="navbar-text col-sm-3">
            <a href="javascript:void(0);" id="logout">로그아웃</a>
        </span>
    </div>
</nav>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/dropzone@5.5.1/dist/dropzone.min.js"></script>

<br>
<div id="formContainer">
    <form action="{% url 'content_create' %}" class="dropzone" id="uploader" style="background-color:whitesmoke;">
        <div class="dz-message" data-dz-message><span>드래그 드랍하거나 클릭하여 이미지 선택</span></div>
        <div class="fallback">
            <input name="file" type="file" />
        </div>
    </form>
    <div class="form-group">
        <label>아래에 글을 입력해주세요.</label>
        <textarea class="form-control rounded-0" id="text" rows="3"></textarea>
    </div>

    <div style="text-align: right;">
        <button type="button" class="btn btn-danger" id="upload">작성하기</button>
    </div>
</div>
{% for content in contents %}
{% for image in content.image_set.all %}
<div class="content">
    <div class="post">
        <div class="text-center user-block">
            <h5 class="text-info left-things">{{ content.user.username }}</h5>
            <img class="img-info img-circle img-bordered-sm" src="{{ image.image.url }}" alt="User Image">

            <div>
                <span class="username left-things">
                    <a href="#" class="text-info">{{ content.user.username }}</a>
                    <a href="#" class="pull-right btn-box-tool"><i class="fa fa-times"></i></a>
                </span>
            </div>
            <p>{{ content.text }}</p>
        </div>
    </div>
</div>
{% endfor %}
{% endfor %}

</div>




<script>
    Dropzone.autoDiscover = false;

    var dropZoneUploader = new Dropzone('form#uploader', {
        init: function () {
            var dropzone = this;

            $('#upload').click(function () {
                dropZoneUploader.processQueue();
            });

            dropzone.on("sending", function (file, xhr, formData) {
                formData.append("text", $('#text').val());
            });
        },
        parallelUploads: 10,
        autoProcessQueue: false,
        type: 'POST',
        success: function () {
            location.reload();
        },
        error: function (e) {
            console.log(e)
            alert('에러가 발생했습니다. 다시 시도해주세요.');
        },
        acceptedFiles: ".jpeg,.jpg,.png,.gif",
        uploadMultiple: true,
    });

    $(document).ready(function () {
        /*
        
        var myDropZone = Dropzone.forElement(".dropzone");
        myDropZone.options.autoProcessQueue = false;
        myDropZone.on("sending", function(file, xhr, data) {
        
                    // First param is the variable name used server side
                    // Second param is the value, you can add what you what
                    // Here I added an input value
                    data.append("your_variable", $('#your_input').val());
                });
        */

        $('#logout').click(function () {
            $.get('/apis/users/logout', {}, function () {
                window.location = '/';
            })
        });
    });
</script>
{% endblock %}

shgram/templates/login.html
{% extends "base.html" %}
{% block body %}
<div id="login">
    <div class="container">
        <br>
        <h3 class="text-center text-warning">Login</h3><br>
        <div class="form-group col-md-6">
            <label for="username" class="text-info">Username:</label><br>
            <input type="text" name="username" id="username" class="form-control">
        </div>
        <div class="form-group col-md-6">
            <label for="password" class="text-info">Password:</label><br>
            <input type="password" name="password" id="password" class="form-control">
        </div>
        <div class="form-group col-md-6">
            <div class="row">
                <input type="submit" id="loginButton" class="form-control btn btn-danger" value="submit">
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="row">
                <a href="{% url 'register' %}" class="form-control btn btn-outline-danger">Register here</a>
            </div>
        </div>

    </div>
</div>




<!--
<h1>로그인</h1>
{{ request.user }}
<input type="text" id="username">
<input type="password" id="password">
<button id="login">로그인</button>

<div class="container">

    <div class="form-group col-md-6">
        <div class="row">
            <a href="{% url 'register' %}" class="form-control btn btn-outline-danger">회원 등록</a>
        </div>
    </div>
</div>
-->


<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        $('#login').click(function () {
            $.post('/apis/users/login', { 'username': $('#username').val(), 'password': $('#password').val() }, function () {
                alert('로그인을 환영합니다!');
                window.location = '/';
            }).fail(function (data) {
                alert(data.responseJSON.message);
            });
        });
    });
</script>
{% endblock %}

shgram/templates/register.html
{% extends "base.html" %}

{% block body %}
<div class="register">
    <div class="col-md-6">
        <h1 class="text-danger">회원 등록</h1>
        <hr>
        <div class="form-group">
            <label for="InputUsername" class="text-danger">아이디</label>
            <input type="text" class="form-control" id="username" placeholder="Enter Username">
        </div>
        <div class="form-group">
            <label for="InputEmail" class="text-danger">Email</label>
            <input type="email" class="form-control" id="email" placeholder="Email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="InputPassword" class="text-danger">비밀번호</label>
            <input type="password" class="form-control" id="password" placeholder="Password">
        </div>
        <button class="btn btn-danger" id="register">등록</button>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    </div>
</div>




<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        $('#register').click(function () {
            $.post('/apis/users/create/', { 'username': $('#username').val(), 'email': $('#email').val(), 'password': $('#password').val() }, function () {
                alert('가입을 환영합니다!');
                window.location = {% url 'login' %};
        }).fail(function (data) {
            alert(data.responseJSON.message);
        });
    });
});
</script>
{% endblock %}

shgram/templates/relation.html
{% include "header.html" %}
{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/dropzone@5.5.1/dist/dropzone.min.css">
{% endblock %}

{% block body %}
<div class="all" style="margin-left: 100px;">
    <p>사용자 찾기</p>
    <input type="text" id="searchUserName" placeholder="유저이름을 입력해주세요.">
    <button id="search" class="btn-outline-danger">검색</button>
    <p><b id="searchResult"></b><span id="searchFollow" style="display: none;"> - <button></button></span></p>
    <hr>

    <h2>날 팔로우 하는 사람들</h2>
    {% if followers  %}
    <ul class="list-group">
        {% for obj in followers %}
        <li class="list-group-item col-md-6">
            {{ obj.follower.username }}{% if obj.follower.id not in followees_ids %} - <button
                class="follow btn btn-outline-danger" data-user-id="{{ obj.follower.id }}">팔로우</button>{% endif %}
        </li>
        {% endfor %}
    </ul>
    {% endif %}


    <h2>내가 팔로우 하는 사람들</h2>
    {% if followees %}
    <ul class="list-group">
        {% for user in followees %}
        <li class="list-group-item col-md-6">{{ user.username }} - <button class="unfollow btn btn-outline-danger"
                data-user-id="{{ user.id }}">언팔로우</button></li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>


<script>

    $(document).ready(function () {

        $('#logout').click(function () {
            $.get('/apis/users/logout', {}, function () {
                location.reload();
            });
        });



        $('#search').click(function () {
            var username = $('#searchUserName').val();
            $.get("{% url 'users_get_info' %}", { username: username }, function (obj) {
                $('#searchResult').html(obj.data.username);

                var $searchRelationButton = $('#searchFollow button');
                $searchRelationButton.data('user-id', obj.data.id);
                console.log(obj.data.id)

                if (username.indexOf(obj.data.id) > -1) {
                    $searchRelationButton.removeClass('follow');
                    $searchRelationButton.addClass('unfollow');
                    $searchRelationButton.html('언팔로우');
                } else {
                    $searchRelationButton.removeClass('unfollow');
                    $searchRelationButton.addClass('follow');
                    $searchRelationButton.html('팔로우');
                }

                $('#searchFollow').show();
            }).fail(function (data) {
                $('#searchResult').html(data.responseJSON.message);
            });
        });

        $('body').delegate('.follow', 'click', function (e) {
            var userId = $(e.currentTarget).data('user-id');
            $.post("{% url 'relation_create' %}", { id: userId }, function () {
                location.reload();
            }).fail(function (data) {
                alert(data.responseJSON.message);
            });
        });

        $('body').delegate('.unfollow', 'click', function (e) {
            var userId = $(e.currentTarget).data('user-id');
            $.post("{% url 'relation_delete' %}", { id: userId }, function () {
                location.reload();
            }).fail(function (data) {
                alert(data.responseJSON.message);
            });
        });
    });
</script>

{% endblock %}